version: '3.8'
services:
   web:
       build: .
       expose:
         - "8001"
       environment:
        DEBUG: 'false'
       volumes:
         - web-static:/layer_transmittance/static/
       ports:
           - "8001:8001"
       command: gunicorn --bind 0.0.0.0:8001 run:app
       networks:
         - trans-network

   nginx:
     build: ./nginx/
     restart: always
     ports:
       - "8081:8081"
     volumes:
       - web-static:/layer_transmittance/static/
     links:
       - web:web
     networks:
       - trans-network
networks:
  trans-network:
    name: trans-network

volumes:
  web-static:
