FROM python:3.9-slim-buster
RUN apt-get update
RUN apt-get install -y g++ zlib1g-dev libjpeg-dev make
RUN pip install --upgrade pip
RUN pip install matplotlib
RUN pip install pandas
RUN pip install scipy==1.4.1
RUN apt-get install -y \
    gcc gfortran musl-dev
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /layer_transmittance
ADD . /layer_transmittance
RUN pip install -r requirements.txt